TELEGRAM_TOKEN: "7898525561:AAEadclW0EFLl7kBOe3144BzqOckFJOg2H8"
WHITELIST_IDS:
  - 155840708
  - 673216588
  - 673216588
  - 69461821
GOOGLE_SHEET_ID: "1Mw-X75_yTpljaHueKgkorCxlXe6GUNMLO-Ixhdtgg1U"
GOOGLE_CREDENTIALS_FILE: "/etc/secrets/credentials_2.json"
RANGE_NAME: "Sheet1!A:F"
