TELEGRAM_TOKEN: "7989593679:AAGNdm7XItdx69avHYzAoysOX64CnUwGTJk"
WHITELIST_IDS:
  - 155840708
  - 673216588
  - 673216588
  - 69461821
GOOGLE_SHEET_ID: "1Mw-X75_yTpljaHueKgkorCxlXe6GUNMLO-Ixhdtgg1U"
GOOGLE_CREDENTIALS_FILE: "credentials.json"
RANGE_NAME: "Sheet1!A:F"
